name: streamflow_android
description: A premium streaming app based on StreamFlow.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.0
  webview_flutter: ^4.4.2
  google_fonts: ^6.1.0
  glassmorphism: ^3.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
